# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f77d4e911808fe9a031c727c476d6f91ada253010f3607412e09e45863827a0104dc28e56cc0f25445917fb2cacd346120db6ccf4c4cb6536debb69742b9d09

test:
  secret_key_base: 32a8521d57cc05ea994dfbfb0448020a06cc254b43443c617e05fe7197b52d2c8aab51f4a2aecfdc712b0177d64604faba0f6751c6ee542125e51b6442e3a502

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
